{
 "title": "Duck Tracker",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ducktracker_active_sessions{instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ducktracker_open_sse_streams{instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "ducktracker_total_points", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of tags",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ducktracker_private_tags{instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ducktracker_public_tags{instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "uptime_seconds{instance=\"localhost:8080\"} / 3600",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}