global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'ducktracker'
    static_configs:
      - targets: ['localhost:8080']
    basic_auth:
      username: 'pass'
      password: 'word'
